### ISSUE TITLE
Can I use it with GROMACS?

### ISSUE THREAD

**Issue by hima111997** [durrantlab/subpex#1]
thank you for this nice tool. but i have a question.
Can I use it with GROMACS? and how?

**Comment by jacobdurrant** [comment]
Thanks for reaching out and expressing interest in using SubPEx. SubPEx is designed to work with NAMD and Amber out of the box. It is not directly compatible with GROMACS. It should be possible to modify the code to make it compatible with GROMACS, although this would require custom adjustments. Best of luck with your project.
